In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a = np.array([1,2,3])

In [4]:
a+15

array([16, 17, 18])

In [5]:
a = [1,2,3,4,5,6,7,8,9,10]
b =[11,12,13,14,15,16,17,18,19,20]
arr_a = np.array(a)
arr_b = np.array(b)

In [6]:
arr_c= arr_a + arr_b
arr_c

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [7]:
type(arr_c)

numpy.ndarray

In [8]:
print(arr_a+arr_b)

[12 14 16 18 20 22 24 26 28 30]


#### ndarray 생성하기

In [9]:
data1= [6,7.5,8,0.1]
arr1 = np.array(data1)

print(arr1)
print(data1)
arr1

[6.  7.5 8.  0.1]
[6, 7.5, 8, 0.1]


array([6. , 7.5, 8. , 0.1])

#### .ndim / .shape / .dtype

In [10]:
arr1.ndim

1

In [11]:
arr1.shape

(4,)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
data2 = [[1,2,3,4],[5,6,7,8,[9,10,11]]]
arr2 = np.array(data2)
arr2

array([list([1, 2, 3, 4]), list([5, 6, 7, 8, [9, 10, 11]])], dtype=object)

In [14]:
print(arr2.ndim)

1


In [15]:
print(arr2.shape)

(2,)


In [16]:
print(arr2.dtype)

object


In [17]:
data3 = [[1,2,3,4],[5,6,7,8]]
arr3 = np.array(data3)
arr3.ndim

2

In [18]:
arr3.shape

(2, 4)

In [19]:
for i in range(5):
    print(i)

0
1
2
3
4


In [20]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [21]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
print(np.empty(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
print(np.eye(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [26]:
print(np.identity(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [27]:
print(np.empty(9))

[0.000e+000 0.000e+000 0.000e+000 0.000e+000 0.000e+000 6.324e-321
 0.000e+000 0.000e+000 0.000e+000]


In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
print(np.eye(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [32]:
print(np.arange(10,20,3))

[10 13 16 19]


In [33]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [34]:
arr1

array([1., 2., 3.])

In [35]:
arr2 = np.array([1,2,3], dtype=np.int8)

In [36]:
arr2

array([1, 2, 3], dtype=int8)

In [37]:
print(arr2.dtype)

int8


In [38]:
arr2_1 = arr2.astype(np.float64)
arr2_1

array([1., 2., 3.])

In [39]:
print(arr2_1.dtype)

float64


In [40]:
np.arange(1-1,6,1)

array([0, 1, 2, 3, 4, 5])

In [41]:
np.arange(1-1,51,9+1)

array([ 0, 10, 20, 30, 40, 50])

In [42]:
np.arange(1-1,51,9+1)[:,np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [43]:
np.arange(0,51,10)[:,np.newaxis] +[1,2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52]])

In [44]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [45]:
a = np.arange(0,50,10)[:,np.newaxis] + np.arange(0,6,1)

In [46]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

In [47]:
a.ndim

2

In [48]:
a.dtype

dtype('int32')

In [49]:
a.shape

(5, 6)

In [50]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
print(arr1>5)

[False False False False False False  True  True  True  True]


In [52]:
print(arr1[arr1>5])

[6 7 8 9]


In [53]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

In [54]:
data = np.random.randint(low=30,high=100,size=(7,4))
print(data)

[[65 73 84 44]
 [97 94 91 39]
 [76 44 49 73]
 [71 38 37 73]
 [67 61 43 96]
 [80 91 80 54]
 [52 90 87 95]]


In [55]:
print(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [56]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [57]:
print(names[names=="Bob"])

['Bob' 'Bob']


In [58]:
print(len(names[names=="Bob"]))

2


In [59]:
data[names=="Bob"]

array([[65, 73, 84, 44],
       [71, 38, 37, 73]])

In [60]:
data[names=="Bob",2:]

array([[84, 44],
       [37, 73]])

In [61]:
data[names=="Bob"][0]

array([65, 73, 84, 44])

In [62]:
data

array([[65, 73, 84, 44],
       [97, 94, 91, 39],
       [76, 44, 49, 73],
       [71, 38, 37, 73],
       [67, 61, 43, 96],
       [80, 91, 80, 54],
       [52, 90, 87, 95]])

In [63]:
names[(names == "Bob") | (names=="Will")]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

In [64]:
data[(names == "Bob") | (names=="Will")]

array([[65, 73, 84, 44],
       [76, 44, 49, 73],
       [71, 38, 37, 73],
       [67, 61, 43, 96]])

In [65]:
data

array([[65, 73, 84, 44],
       [97, 94, 91, 39],
       [76, 44, 49, 73],
       [71, 38, 37, 73],
       [67, 61, 43, 96],
       [80, 91, 80, 54],
       [52, 90, 87, 95]])

In [67]:
data[data <=70] = 0

In [69]:
data[data>70]=1

In [70]:
data

array([[0, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 1, 0],
       [0, 1, 1, 1]])

In [71]:
np.where(data>0)

(array([0, 0, 1, 1, 1, 2, 2, 3, 3, 4, 5, 5, 5, 6, 6, 6], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 3, 0, 3, 3, 0, 1, 2, 1, 2, 3], dtype=int64))

In [72]:
np.where(data==0)

(array([0, 0, 1, 2, 2, 3, 3, 4, 4, 4, 5, 6], dtype=int64),
 array([0, 3, 3, 1, 2, 1, 2, 0, 1, 2, 3, 0], dtype=int64))

In [73]:
np.where(data>0)[0]

array([0, 0, 1, 1, 1, 2, 2, 3, 3, 4, 5, 5, 5, 6, 6, 6], dtype=int64)

In [75]:
print(np.unique(np.where(data>0)[0]))

[0 1 2 3 4 5 6]


In [76]:
print(names[np.unique(np.where(data>0)[0])])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [77]:
arr1 = np.arange(64)

In [78]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [82]:
arr1 = arr1.reshape((8,8))
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [83]:
arr1.ndim

2

In [85]:
arr1 = arr1.reshape((4,16))
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [86]:
arr1= arr1.reshape((8,8))
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [87]:
arr1.T

array([[ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

In [88]:
list = [1,4,9,16,25,36,49,64]
arr = np.array(list)

In [89]:
arr

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [90]:
arr = np.sqrt(arr)

In [91]:
arr

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [92]:
arr1 = arr
arr2 = np.arange(10)

In [98]:
arr = np.random.randn(4,4)
print(arr)

[[ 0.19421196 -0.49773078 -0.22304997 -2.00593745]
 [ 0.31103147  0.89942002  0.17887628 -1.5027546 ]
 [-0.33061142 -1.25329726 -1.01695066 -2.39949813]
 [ 0.69768113  0.97484715 -0.27011371 -1.0579248 ]]


In [99]:
print(np.where(arr>0,2,-2))

[[ 2 -2 -2 -2]
 [ 2  2  2 -2]
 [-2 -2 -2 -2]
 [ 2  2 -2 -2]]


In [100]:
print(np.where(arr>0,2,arr))

[[ 2.         -0.49773078 -0.22304997 -2.00593745]
 [ 2.          2.          2.         -1.5027546 ]
 [-0.33061142 -1.25329726 -1.01695066 -2.39949813]
 [ 2.          2.         -0.27011371 -1.0579248 ]]


In [101]:
arr

array([[ 0.19421196, -0.49773078, -0.22304997, -2.00593745],
       [ 0.31103147,  0.89942002,  0.17887628, -1.5027546 ],
       [-0.33061142, -1.25329726, -1.01695066, -2.39949813],
       [ 0.69768113,  0.97484715, -0.27011371, -1.0579248 ]])

In [105]:
print(np.where((arr>0)&(arr<0.1),2,-2))

[[-2 -2 -2 -2]
 [-2 -2 -2 -2]
 [-2 -2 -2 -2]
 [-2 -2 -2 -2]]


In [106]:
arr = np.random.randn(8)

In [107]:
arr

array([-0.20301039,  0.0733069 , -0.60523929,  1.16122735, -2.04851873,
       -0.96565877,  0.6989159 ,  0.58868532])

In [108]:
print(arr.sort())

None


In [109]:
arr.sort()

In [110]:
arr

array([-2.04851873, -0.96565877, -0.60523929, -0.20301039,  0.0733069 ,
        0.58868532,  0.6989159 ,  1.16122735])

In [111]:
print(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [112]:
print(np.unique(names))

['Bob' 'Joe' 'Will']
