In [1]:
import pandas as pd
import numpy as np

In [2]:
s_price = [11600,11550,12000,12200,11650]
s_priceSeries = pd.Series(s_price)
s_priceSeries

0    11600
1    11550
2    12000
3    12200
4    11650
dtype: int64

In [3]:
s_priceSeries[3]

12200

In [4]:
s_priceSeries = pd.Series(s_price, index=["2020-06-26","2020-06-25","2020-06-24","2020-06-23","2020-06-22"])

In [5]:
s_priceSeries

2020-06-26    11600
2020-06-25    11550
2020-06-24    12000
2020-06-23    12200
2020-06-22    11650
dtype: int64

In [6]:
s_priceSeries["2020-06-26"]

11600

In [7]:
s_priceSeries["2020-06-22"]

11650

In [8]:
s_priceSeries.index

Index(['2020-06-26', '2020-06-25', '2020-06-24', '2020-06-23', '2020-06-22'], dtype='object')

In [14]:
s_priceSeries.index[0]

'2'

In [10]:
s_priceSeries.index[2]

'2020-06-24'

In [16]:
for i in s_priceSeries.index:
    print(i)
    print(s_priceSeries[i])

2020-06-26
11600
2020-06-25
11550
2020-06-24
12000
2020-06-23
12200
2020-06-22
11650


In [17]:
s_priceSeries.values

array([11600, 11550, 12000, 12200, 11650], dtype=int64)

In [18]:
for i in s_priceSeries.values:
    print(i)

11600
11550
12000
12200
11650


In [19]:
s_priceSeries["2020-06-25"]

11550

In [27]:
for i in range(len(s_priceSeries)):
    print(s_priceSeries.index[i])
    print(s_priceSeries[i])
    
for i in s_priceSeries.index:
    print(i)
    print(s_priceSeries[i])

2020-06-26
11600
2020-06-25
11550
2020-06-24
12000
2020-06-23
12200
2020-06-22
11650
2020-06-26
11600
2020-06-25
11550
2020-06-24
12000
2020-06-23
12200
2020-06-22
11650


In [28]:
s_priceSeries[[1,3,4]]

2020-06-25    11550
2020-06-23    12200
2020-06-22    11650
dtype: int64

In [29]:
s_priceSeries[["2020-06-25","2020-06-22"]]

2020-06-25    11550
2020-06-22    11650
dtype: int64

In [30]:
s_priceSeries

2020-06-26    11600
2020-06-25    11550
2020-06-24    12000
2020-06-23    12200
2020-06-22    11650
dtype: int64

In [31]:
s_priceSeries *2

2020-06-26    23200
2020-06-25    23100
2020-06-24    24000
2020-06-23    24400
2020-06-22    23300
dtype: int64

In [32]:
np.add(s_priceSeries, 100)

2020-06-26    11700
2020-06-25    11650
2020-06-24    12100
2020-06-23    12300
2020-06-22    11750
dtype: int64

In [34]:
s_priceSeries[s_priceSeries > 12000]

2020-06-23    12200
dtype: int64

In [35]:
"2020-06-23" in s_priceSeries

True

#### value면은 in을 이용할 수 없구나!!

In [36]:
sdata = {"APPL": 1000, "MS":2000,"AMAZON":3000}

In [37]:
obj3 = pd.Series(sdata)

In [38]:
obj3

APPL      1000
MS        2000
AMAZON    3000
dtype: int64

In [41]:
states = ["GOOGLE","APPL","AMAZON"]
obj4 = pd.Series(sdata, states)
obj4

GOOGLE       NaN
APPL      1000.0
AMAZON    3000.0
dtype: float64

In [42]:
print(obj3 + obj4)

AMAZON    6000.0
APPL      2000.0
GOOGLE       NaN
MS           NaN
dtype: float64


In [43]:
print(obj3 - obj4)

AMAZON    0.0
APPL      0.0
GOOGLE    NaN
MS        NaN
dtype: float64


#### isnull notull 

In [44]:
vals = np.array([1,None,3,4])
vals

array([1, None, 3, 4], dtype=object)

In [45]:
pd.isnull(vals)

array([False,  True, False, False])

In [46]:
pd.notnull(vals)

array([ True, False,  True,  True])

In [47]:
s_priceSeries

2020-06-26    11600
2020-06-25    11550
2020-06-24    12000
2020-06-23    12200
2020-06-22    11650
dtype: int64

In [48]:
pd.isnull(s_priceSeries)

2020-06-26    False
2020-06-25    False
2020-06-24    False
2020-06-23    False
2020-06-22    False
dtype: bool

In [50]:
s_priceSeries["2020-06-21"] = None

In [51]:
s_priceSeries

2020-06-26    11600
2020-06-25    11550
2020-06-24    12000
2020-06-23    12200
2020-06-22    11650
2020-06-21     None
dtype: object

In [52]:
pd.isnull(s_priceSeries)

2020-06-26    False
2020-06-25    False
2020-06-24    False
2020-06-23    False
2020-06-22    False
2020-06-21     True
dtype: bool

In [53]:
s_priceSeries.isnull()

2020-06-26    False
2020-06-25    False
2020-06-24    False
2020-06-23    False
2020-06-22    False
2020-06-21     True
dtype: bool

In [54]:
s_priceSeries.index

Index(['2020-06-26', '2020-06-25', '2020-06-24', '2020-06-23', '2020-06-22',
       '2020-06-21'],
      dtype='object')

In [55]:
s_priceSeries.index.name = "Stock Price Date"

In [56]:
s_priceSeries

Stock Price Date
2020-06-26    11600
2020-06-25    11550
2020-06-24    12000
2020-06-23    12200
2020-06-22    11650
2020-06-21     None
dtype: object

In [57]:
s_priceSeries.ndim

1

In [58]:
s_priceSeries.shape

(6,)

In [59]:
s_priceSeries.size

6

In [60]:
s_priceSeries.count()

5

In [61]:
s_priceSeries.max()

12200

In [62]:
s_priceSeries.min()

11550

In [63]:
s_priceSeries.mean()

11800.0

In [67]:
add_data = pd.Series([13000], index =["2020-06-20"])
s_priceSeries.append(add_data)

2020-06-26    11600
2020-06-25    11550
2020-06-24    12000
2020-06-23    12200
2020-06-22    11650
2020-06-21     None
2020-06-20    13000
dtype: object

In [68]:
data0619 = pd.Series([11800],index=["2020-06-19"])

In [71]:
s_priceSeries = s_priceSeries.append(data0619)

In [72]:
s_priceSeries

2020-06-26    11600
2020-06-25    11550
2020-06-24    12000
2020-06-23    12200
2020-06-22    11650
2020-06-21     None
2020-06-19    11800
dtype: object

In [74]:
print(s_priceSeries.max())

12200


In [75]:
print(s_priceSeries.min())

11550


In [76]:
print(s_priceSeries.mean())

11800.0


In [77]:
print(s_priceSeries.cummin())

2020-06-26    11600
2020-06-25    11550
2020-06-24    11550
2020-06-23    11550
2020-06-22    11550
2020-06-21      NaN
2020-06-19    11550
dtype: object


In [78]:
s_priceSeries.std()

254.95097567963924

In [79]:
s_priceSeries.var()

65000.0